### ISSUE TITLE
Readme needs an update

### ISSUE THREAD

**Issue by dimpase** [gap-packages/RepnDecomp#1]
It's not a project, it's a package...

**Comment by kaashif** [comment]
Yes, if there are any updates you want to make, you can do so now. I have added you as an admin (and merged #2, which adds you to the PackageInfo.g as a maintainer).

**Comment by olexandr-konovalov** [comment]
One should also update CI (Travis, AppVeyor, Codecov) after migrating the repository.

**Comment by olexandr-konovalov** [comment]
Noticed that you have used travis-ci.com - can I update settings to use travis-ci.org like for all other packages in this organisation?

**Comment by kaashif** [comment]
I actually didn't even notice that. Reading about it now, I think that [Travis CI wants people to make all new repositories on travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#new-repositories) though. I don't think there is any real difference between them, if you want to move over for consistency, that's fine with me.

**Comment by kaashif** [comment]
I think I addressed this in some changes I made to the readme a while ago.

**Comment by olexandr-konovalov** [comment]
Thanks, but the Travis CI badge is still pointing elsewhere. I have submitted PR #6 to switch to our standard setup.
