### ISSUE TITLE
Has this package completely replaced the decomp package?

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/RepnDecomp#18]
I also noticed the [decomp](https://gitlab.com/kaashif/decomp) package, so I want to know whether this package has completely replaced/superseded/obsoleted the decomp package. 

Regards,
Zhao

**Comment by kaashif** [comment]
Hello, yes, that repo you linked has a pretty old version of the code, and dates back to before this package was added to GAP.

I should just delete it, probably - the git history from that repo is preserved in this repo.

**Comment by dimpase** [comment]
@kaashif - you can just archive it.
