### ISSUE TITLE
About many functions defined in this package with the suffix `@`.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/RepnDecomp#20]
I noticed that so many functions were defined in this package to have the suffix `@`, such as following one:

https://github.com/gap-packages/RepnDecomp/blob/f9a5cc6611d763503cc2ff24822cae9190ea1943/lib/utils.gi#L238-L240

IMO, this is a rather uncommon method in GAP. It seems that the goal here is to imitate the prefix form in Wolfram language. However, due to the different basic design principles of the two languages, the final effect is still quite different. For example, in many cases, parentheses cannot be omitted in the GAP language, resulting in the frequent use of redundant `@` characters, just as in the following usage:

https://github.com/gap-packages/RepnDecomp/blob/f9a5cc6611d763503cc2ff24822cae9190ea1943/lib/utils.gi#L32

In the above usage, it's obvious that `Replicate(0, len2)` is more concise than `Replicate@(0, len2)`. I am not sure whether my understanding is correct, and I would appreciate any explanation for this problem.

Regards,
Zhao

**Comment by kaashif** [comment]
> It seems that the goal here is to imitate the prefix form in Wolfram language.

Interesting guess, but that's not the reason for the `@` symbols, I've never written any code in Wolfram.

If you look at section 4.10 "Namespaces for GAP packages" of https://docs.gap-system.org/doc/ref/manual.pdf (page 55 at the time I'm writing this comment), you'll see an explanation. The @ symbol is a way of namespacing symbols to this package.

Within this package, whenever you see an identifier like `ConjugateTranspose@`, GAP will translate this to `ConjugateTranspose@RepnDecomp`. This feature is useful to prevent name clashes with other packages. I'm sure many packages have functions called `ConjugateTranspose`, but if they use `@`, then theirs will be in their namespace `ConjugateTranspose@TheirPackage` and ours in our namespace `ConjugateTranspose@RepnDecomp`.

It's really just a convenience feature so we don't have to suffix or prefix all of the variables and functions we want to have unique names.

Not the most obvious or googleable syntax, I guess.

**Comment by hongyi-zhao** [comment]
> If you look at section 4.10 "Namespaces for GAP packages" of https://docs.gap-system.org/doc/ref/manual.pdf (page 55 at the time I'm writing this comment), you'll see an explanation. The @ symbol is a way of namespacing symbols to this package.

Thank you for pointing this out. The online HTML version is [here](https://docs.gap-system.org/doc/ref/chap4.html#X7DF8774F7D542298).

> Within this package, whenever you see an identifier like `ConjugateTranspose@`, GAP will translate this to `ConjugateTranspose@RepnDecomp`.

Below is the example given by Dima Pasechnik [here](https://lists.uni-kl.de/gap/arc/forum/2022-10/msg00020.html):

```gap
Dear Zhao, dear all,

you can run the following:

gensD8:=[ # these are your matrices generating D8
[[0,1,0,0,0,0,0,0],
[0,0,1,0,0,0,0,0],
[0,0,0,1,0,0,0,0],
[1,0,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0],
[0,0,0,0,0,0,1,0],
[0,0,0,0,0,0,0,1],
[0,0,0,0,1,0,0,0]],
[[0,0,0,0,1,0,0,0],
[0,0,0,0,0,0,0,1],
[0,0,0,0,0,0,1,0],
[0,0,0,0,0,1,0,0],
[1,0,0,0,0,0,0,0],
[0,0,0,1,0,0,0,0],
[0,0,1,0,0,0,0,0],
[0,1,0,0,0,0,0,0]]
];;
D8:=Group(gensD8);
LoadPackage("RepnDecomp");
tau:=FuncToHom@RepnDecomp(D8,h->h);
bl:=BlockDiagonalRepresentation(tau);
bdiagD8:=Image(bl);
Display(bdiagD8.1); # these are two generators in block-diag. form
Display(bdiagD8.2);
Display(BlockDiagonalBasisOfRepresentation(tau)); # this is the transforming
matrix


----------

The last part of the output:

[ [ 1, 0, 0, 0, 0, 0, 0, 0 ],
[ 0, 1, 0, 0, 0, 0, 0, 0 ],
[ 0, 0, -1, 0, 0, 0, 0, 0 ],
[ 0, 0, 0, -1, 0, 0, 0, 0 ],
[ 0, 0, 0, 0, E(4), 0, 0, 0 ],
[ 0, 0, 0, 0, 0, -E(4), 0, 0 ],
[ 0, 0, 0, 0, 0, 0, E(4), 0 ],
[ 0, 0, 0, 0, 0, 0, 0, -E(4) ] ]
[ [ 1, 0, 0, 0, 0, 0, 0, 0 ],
[ 0, -1, 0, 0, 0, 0, 0, 0 ],
[ 0, 0, 1, 0, 0, 0, 0, 0 ],
[ 0, 0, 0, -1, 0, 0, 0, 0 ],
[ 0, 0, 0, 0, 0, 1, 0, 0 ],
[ 0, 0, 0, 0, 1, 0, 0, 0 ],
[ 0, 0, 0, 0, 0, 0, 0, 1 ],
[ 0, 0, 0, 0, 0, 0, 1, 0 ] ]

[ [ 1, 1, 1, 1, 1, 1, 1, 1 ],
[ 1, 1, 1, 1, -1, -1, -1, -1 ],
[ 1, -1, 1, -1, 1, -1, 1, -1 ],
[ 1, -1, 1, -1, -1, 1, -1, 1 ],
[ 1, E(4), -1, -E(4), 0, 0, 0, 0 ],
[ 0, 0, 0, 0, 1, -E(4), -1, E(4) ],
[ 0, 0, 0, 0, 1, E(4), -1, -E(4) ],
[ 1, -E(4), -1, E(4), 0, 0, 0, 0 ] ]

HTH
Dima
```
According to your above comment, it seems that the following form used in the above example is adequate:

`tau:=FuncToHom@(D8,h->h);`

To confirm this problem, the following tests were performed:

```gap
gap> FuncToHom@RepnDecomp(D8,h->h);
CompositionMapping( [ (1,2,3,4), (2,4) ] -> [ [ [ 0, 1, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 1, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 1, 0, 0, 0, 0 ], [ 1, 0, 0, 0, 0, 0, 0, 0 ], 
      [ 0, 0, 0, 0, 0, 1, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 1, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 1, 0, 0, 0 ] ], 
  [ [ 0, 0, 0, 0, 1, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 0, 0, 1, 0 ], [ 0, 0, 0, 0, 0, 1, 0, 0 ], 
      [ 1, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 1, 0, 0, 0, 0 ], [ 0, 0, 1, 0, 0, 0, 0, 0 ], [ 0, 1, 0, 0, 0, 0, 0, 0 ] ] ], CompositionMapping( 
[ (4,5)(6,7)(8,9,10,11)(12,13,14,15), (2,3)(6,7)(9,11)(13,15) ] -> [ (1,2,3,4), (2,4) ], <action isomorphism> ) )
gap> FuncToHom@(D8,h->h);
Error, Variable: 'FuncToHom@' must have a value
not in any function at *stdin*:89
```

As you can see, in this test, `FuncToHom@(D8,h->h);` actually doesn't work. So, I'm still a little confused about this kind of naming space. Any further comments will be appreciated.

Regards,
Zhao

**Comment by kaashif** [comment]
This is clarified a bit in the manual, when I say "within this package", I mean something specific:

> If in package code a global variable that ends with an “at”-character @ is accessed in any way, the name of the package is appended before accessing it. Here, “package code” refers to everything which is read with ReadPackage (76.3.1). As the name of the package the entry PackageName in its PackageInfo.g file is taken.

The code for this package is loaded (and the translation of @ names done) because of the ReadPackage lines in https://github.com/gap-packages/RepnDecomp/blob/master/read.g - the @ translation only happens for the files specified there.

The GAP REPL is not code loaded with ReadPackage, so the name translation of `FuncToHom@` to `FuncToHom@RepnDecomp` is not done there.

**Comment by hongyi-zhao** [comment]
> The code for this package is loaded (and the translation of @ names done) because of the ReadPackage lines in https://github.com/gap-packages/RepnDecomp/blob/master/read.g -

The above file has the following line in it:

https://github.com/gap-packages/RepnDecomp/blob/f9a5cc6611d763503cc2ff24822cae9190ea1943/read.g#L13

And furthermore, the `FuncToHom@` is defined in the file which is already included in [read.g](https://github.com/gap-packages/RepnDecomp/blob/master/read.g) as shown above:
```gap
werner@X10DAi-00:~/.gap/pkg/RepnDecomp$ rg '^FuncToHom@' -g '*.gi'
lib/utils.gi
83:FuncToHom@ := function(G, f)
```

> the @ translation only happens for the files specified there.

Why does the expected behavior described above still not occur in this case?

> The GAP REPL is not code loaded with ReadPackage, 

So, when does this behavior happen?

> so the name translation of `FuncToHom@` to `FuncToHom@RepnDecomp` is not done there.

If I always need to call this function with the form `FuncToHom@RepnDecomp` in my GAP script, then I really don't know what advantages this method has.
