### ISSUE TITLE
How to accommodate upcoming changed pluralisation in GAP?

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/RepnDecomp#9]
I am working on https://github.com/gap-system/gap/pull/4050, which means that in a future version of GAP, some nouns will be correctly pluralised to match their number.  For example, the `ViewString` for `CyclicGroup(3);` will change from `<pc group of size 3 with 1 generators>` to `<pc group of size 3 with 1 generator>`.

This will break one test in this package, the final one derived from this manual example:

https://github.com/gap-packages/RepnDecomp/blob/8c41a28035acf8bd2fa2b32150719ee438ce8e78/examples/serre.g#L4-L20

When run in some upcoming new version of GAP, the text on the final line will read `<vector space over Cyclotomics, with 1 generator>` (i.e. the final `s` is removed).

How should I (I am happy to make a PR) adjust this example to maintain backwards compatibility with GAP 4.10 and 4.11? Simply removing the `s` would mean that this test fails in these older versions of GAP.

Would it be acceptable to change the final lines to read:
```
gap> canonical_summands_H := CanonicalDecomposition(tau);;
gap> canonical_summands_H[1];
<vector space over Cyclotomics, with 2 generators>
gap> List(canonical_summands_H, Dimension);
[ 2, 1 ]
```
? Or indeed just:
```
gap> List(CanonicalDecomposition(tau), Dimension);
[ 2, 1 ]
```

**Comment by olexandr-konovalov** [comment]
Question to @dimpase and @kaashif - how critical is to see details which @wilfwilson suggests to hide?

**Comment by dimpase** [comment]
I will have a look once back to Oxford tonight.

**Comment by dimpase** [comment]
it is a shame that GAP tests don't allow wildcards for this kind of cases.

**Comment by dimpase** [comment]
but yes, the proposed change will do.

**Comment by kaashif** [comment]
The point of the test is really just to see the dimensions so the proposed change, preferably the second one which just shows the dimensions, is fine by me.

All of the vector spaces in the whole package are over Cyclotomics, so that detail doesn't really matter in this case.

**Comment by fingolfin** [comment]
So hopefully @wilfwilson can proceed based on this. Great!

**Comment by wilfwilson** [comment]
Yep, thanks for the nudge @fingolfin.
